# Generated by Django 5.2.6 on 2025-10-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('contract', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
