# Generated by Django 5.2.6 on 2025-10-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='salary',
            field=models.FloatField(max_length=50),
        ),
    ]
