# Generated by Django 5.2.6 on 2025-10-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first1', '0002_alter_details_email_alter_details_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
