# Generated by Django 5.2.6 on 2025-10-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first1', '0003_details_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='City',
        ),
        migrations.RemoveField(
            model_name='details',
            name='username',
        ),
    ]
